import jsPDF from 'jspdf'
import { generateReport } from './api'

const BG     = [8, 8, 8]
const CARD   = [24, 23, 0]
const GOLD   = [212, 175, 55]
const GOLD_B = [255, 215, 0]
const TEXT   = [240, 238, 213]
const MUTED  = [122, 119, 96]
const BORDER = [42, 40, 0]

function setFill(pdf, [r, g, b]) { pdf.setFillColor(r, g, b) }
function setDraw(pdf, [r, g, b]) { pdf.setDrawColor(r, g, b) }
function setTxt(pdf, [r, g, b])  { pdf.setTextColor(r, g, b) }

function darkPage(pdf) {
  setFill(pdf, BG)
  pdf.rect(0, 0, 210, 297, 'F')
}

function sectionRule(pdf, x, y, w) {
  setDraw(pdf, GOLD)
  pdf.setLineWidth(0.4)
  pdf.line(x, y, x + w, y)
}

export async function downloadPdfReport(symbol, start, end, predDays, futureDays) {
  const data = await generateReport(symbol, start, end, predDays, futureDays)

  const pdf      = new jsPDF('p', 'mm', 'a4')
  const W        = 210
  const H        = 297
  const margin   = 14
  const cW       = W - 2 * margin
  const m        = data.metrics

  // ── Cover page ────────────────────────────────────────────────────────────
  darkPage(pdf)

  // Gold accent bar
  setFill(pdf, GOLD)
  pdf.rect(0, 0, 5, H, 'F')

  // Title
  setTxt(pdf, GOLD_B)
  pdf.setFontSize(28)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Stock Price', margin + 8, 55)
  pdf.text('Analysis Report', margin + 8, 68)

  setTxt(pdf, GOLD)
  pdf.setFontSize(36)
  pdf.text(symbol, margin + 8, 92)

  // Metadata
  setTxt(pdf, MUTED)
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Period: ${m.start}  →  ${m.end}`, margin + 8, 106)
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin + 8, 113)
  pdf.text('Model: Random Forest Regressor (100 Estimators)', margin + 8, 120)

  // Metrics cards
  const cards = [
    { label: 'Current Price',       value: `$${m.current_price.toFixed(2)}`,  color: GOLD },
    { label: 'Predicted Next Day',  value: `$${m.predicted_next.toFixed(2)}`, color: GOLD_B },
    { label: 'RMSE',                value: `$${m.rmse.toFixed(2)}`,           color: [100, 165, 250] },
    { label: 'Accuracy',            value: `${m.accuracy.toFixed(1)}%`,       color: [74, 222, 128] },
  ]

  cards.forEach((c, i) => {
    const cx = margin + 8 + i * (cW / 4)
    const cy = 138
    const cw = cW / 4 - 3
    setFill(pdf, CARD)
    setDraw(pdf, BORDER)
    pdf.roundedRect(cx, cy, cw, 28, 2, 2, 'FD')
    setTxt(pdf, MUTED)
    pdf.setFontSize(7.5)
    pdf.setFont('helvetica', 'normal')
    pdf.text(c.label.toUpperCase(), cx + 4, cy + 9)
    setTxt(pdf, c.color)
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'bold')
    pdf.text(c.value, cx + 4, cy + 22)
  })

  // Disclaimer
  sectionRule(pdf, margin + 8, 192, cW)
  setTxt(pdf, MUTED)
  pdf.setFontSize(8)
  pdf.setFont('helvetica', 'italic')
  const disc = 'Disclaimer: This report is generated by a machine learning model for educational purposes only. Stock market predictions are inherently uncertain and should not be used as the sole basis for investment decisions.'
  const discLines = pdf.splitTextToSize(disc, cW)
  pdf.text(discLines, margin + 8, 198)

  // Footer
  setTxt(pdf, BORDER)
  pdf.setFontSize(7.5)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`${symbol} Stock Report  |  StockPredictML  |  Page 1`, margin, H - 8)

  // ── Chart pages ───────────────────────────────────────────────────────────
  for (let ci = 0; ci < data.charts.length; ci++) {
    const chart = data.charts[ci]
    pdf.addPage()
    darkPage(pdf)
    setFill(pdf, GOLD)
    pdf.rect(0, 0, 5, H, 'F')

    let y = 20

    // Chart title
    setTxt(pdf, GOLD)
    pdf.setFontSize(15)
    pdf.setFont('helvetica', 'bold')
    pdf.text(`${ci + 1}. ${chart.title}`, margin + 8, y)
    y += 5
    sectionRule(pdf, margin + 8, y, cW)
    y += 8

    // Chart image
    const imgH = 75
    try {
      pdf.addImage(chart.image, 'PNG', margin + 8, y, cW, imgH)
    } catch (e) {
      setTxt(pdf, MUTED)
      pdf.setFontSize(9)
      pdf.text('[Chart image unavailable]', margin + 8, y + 30)
    }
    y += imgH + 8

    // Description heading
    setTxt(pdf, GOLD_B)
    pdf.setFontSize(9.5)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Analysis', margin + 8, y)
    y += 5

    // Description body
    setTxt(pdf, TEXT)
    pdf.setFontSize(8.5)
    pdf.setFont('helvetica', 'normal')
    const lines = pdf.splitTextToSize(chart.description, cW)
    pdf.text(lines, margin + 8, y)
    y += lines.length * 4.8 + 10

    // Interpretation box
    const interpretation = getInterpretation(chart.id, m, symbol)
    if (interpretation) {
      setFill(pdf, CARD)
      setDraw(pdf, BORDER)
      const boxLines = pdf.splitTextToSize(`Key Insight: ${interpretation}`, cW - 8)
      const boxH = boxLines.length * 5 + 10
      if (y + boxH < H - 15) {
        pdf.roundedRect(margin + 8, y, cW, boxH, 2, 2, 'FD')
        setTxt(pdf, GOLD)
        pdf.setFontSize(8)
        pdf.setFont('helvetica', 'bold')
        pdf.text(`Key Insight: `, margin + 12, y + 7)
        setTxt(pdf, TEXT)
        pdf.setFont('helvetica', 'normal')
        pdf.text(boxLines, margin + 12, y + 7)
        y += boxH + 5
      }
    }

    setTxt(pdf, BORDER)
    pdf.setFontSize(7.5)
    pdf.setFont('helvetica', 'normal')
    pdf.text(`${symbol} Stock Report  |  StockPredictML  |  Page ${ci + 2}`, margin, H - 8)
  }

  pdf.save(`${symbol}_stock_analysis_${new Date().toISOString().slice(0, 10)}.pdf`)
}

function getInterpretation(chartId, m, symbol) {
  const dir = m.predicted_next > m.current_price ? 'bullish' : 'bearish'
  const chg = ((m.predicted_next - m.current_price) / m.current_price * 100).toFixed(2)
  switch (chartId) {
    case 'history':
      return `The overall price trend for ${symbol} over the selected period indicates ${m.pct_change >= 0 ? 'positive momentum' : 'a downtrend'}. Sustained moves above the opening price suggest accumulation.`
    case 'sma':
      return 'Monitor SMA crossovers closely — a 20-Day SMA crossing above the 100-Day SMA (Golden Cross) is a classic bullish signal. A Death Cross (opposite) may signal a trend reversal.'
    case 'avp':
      return `The model achieved ${m.accuracy.toFixed(1)}% accuracy on unseen test data with RMSE of $${m.rmse.toFixed(2)}. Lower RMSE relative to the stock price indicates high prediction confidence.`
    case 'future':
      return `The model projects a ${dir} short-term outlook with ${chg}% expected move from the current price of $${m.current_price.toFixed(2)}. Use in conjunction with fundamental analysis.`
    case 'dist':
      return 'Price distribution shape reveals market sentiment — right-skewed distributions suggest occasional large up-moves (momentum plays), while left-skew indicates downside risk.'
    case 'corr':
      return 'Strong OHLC correlations are expected. Watch for unusual Volume-Close correlations: high volume with rising close confirms trend strength; high volume with declining close signals distribution.'
    default:
      return null
  }
}
